github: [implement-from-scratch]
patreon: implementfromscratch # Add your Patreon username once created
open_collective: # Not using yet
ko_fi: # Not using yet
tidelift: # Not using yet
community_bridge: # Deprecated platform
liberapay: # Not using yet
issuehunt: # Not using yet
lfx_crowdfunding: # Not using yet
polar: # Not using yet
buy_me_a_coffee: # Not using yet
thanks_dev: # Not using yet
custom: ['https://website-seven-murex-43.vercel.app'] # Your organization website
